### ISSUE TITLE
cpp: rolling hash need to take the reference of the string not the copy

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/cpstl#35]
We have the following code in https://github.com/vincenzopalazzo/cpstl/tree/master/cpp/algoritmins/karp_rabin_fingerprint

```
  T hash(std::string value) {
    auto vector_bytes = string_to_to_bytes(value);
    // x' = ((x « 1) + bit[i]) % p
    for (std::size_t i = 1; i < vector_bytes.size(); i++) {
      vector_bytes[i] = (vector_bytes[i - 1] + vector_bytes[i]) % prime_number;
    }
    return vector_bytes.back();
  }
```

We just need the reference of the string, so some things like that

```
  T hash(std::string const &value) {
    auto vector_bytes = string_to_to_bytes(value);
    // x' = ((x « 1) + bit[i]) % p
    for (std::size_t i = 1; i < vector_bytes.size(); i++) {
      vector_bytes[i] = (vector_bytes[i - 1] + vector_bytes[i]) % prime_number;
    }
    return vector_bytes.back();
  }
```

**Comment by Mouradouchane** [comment]
hi man , i think i can do that 😄

**Comment by vincenzopalazzo** [comment]
Hi @Mouradouchane,

Ops I just fixed this, because I found a bug in my implementation. Do you want to take any other task? What do you like to do on this repository? I can help you to start if you want

**Comment by Mouradouchane** [comment]
thanks @vincenzopalazzo  , i am currently ,"studying and training" on data-structures using C++
i think , i can help in that topic

**Comment by vincenzopalazzo** [comment]
@Mouradouchane It is amazing, I will be happy to review your PR, and maybe discuss what we need to support from a data structure point of view, by open a new discussion :)

**Comment by Mouradouchane** [comment]
currently i am working on dynamic_tree , you can take a look on it 
https://github.com/Mouradouchane/data_structures/blob/main/data_structures/trees/dynamic_tree.hpp

if you want , we can add it here in that repo and improve it .

**Comment by vincenzopalazzo** [comment]
>if you want , we can add it here in that repo and improve it .

Of curse, I would love someone that help me to improve this repository. I have only one rule, I love to use the C++ guideline in the repository. So, we need to change a little bit style of the code but I think it is not a big deal, right?

**Comment by Mouradouchane** [comment]
yeah sure no problem 😄

**Comment by Mouradouchane** [comment]
hi , man you have any social media account telegram or instagram or ... 😀

**Comment by vincenzopalazzo** [comment]
>hi , man you have any social media account telegram or instagram or ... grinning
All listed here https://github.com/vincenzopalazzo

BTW, there is also discord with `vincenzopalazzo` nickname

**Comment by Mouradouchane** [comment]
discord name missing #numbers 😄 => vincenzopalazzo#xxxx

**Comment by vincenzopalazzo** [comment]
>discord name missing #numbers smile => vincenzopalazzo#xxxx

Ops! Sorry `vincenzopalazzo#3884`
